db:
  host: localhost
  port: 8010
  user: health
  password: gin-template123
  name: gin-template

port: 8220

zap:
  level: info
  format: console
  prefix: "[gin-template]"
#  director: log 执行路径目前
  director: ./log
  show-line: true
  encode-level: "LowercaseColorLevelEncoder"
  stacktrace-key: stacktrace
  log-in-console: true
